# Generated by Django 4.1.2 on 2022-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='terminos',
            field=models.BooleanField(default=True),
        ),
    ]
