# Generated by Django 4.1 on 2022-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_libro_imagen_libro_nombre_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.FloatField(),
        ),
    ]
