# Generated by Django 4.1 on 2022-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_libro_digital_alter_libro_nombre_alter_libro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='digital',
        ),
    ]
