# Generated by Django 4.1 on 2022-11-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_libro_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen',
        ),
    ]
