# Generated by Django 4.1.2 on 2022-11-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20221127_1312'),
        ('app', '0005_remove_libro_imagen'),
    ]

    operations = [
    ]
