# Generated by Django 4.1.2 on 2022-11-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20221127_1926'),
        ('app', '0009_alter_libro_imagen'),
    ]

    operations = [
    ]
