# Generated by Django 4.1.2 on 2022-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20221128_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='IniciarSesion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
