# Generated by Django 4.1.2 on 2022-11-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_libro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='description',
        ),
    ]
