# Generated by Django 4.1.2 on 2022-11-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_descripcion_libro_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='description',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
    ]
