# Generated by Django 4.1.2 on 2022-11-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
