# Generated by Django 4.1.2 on 2022-11-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_libro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
    ]
