# Generated by Django 4.1.2 on 2022-11-30 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_rename_descripcion_libro_texto_remove_libro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
