# Generated by Django 4.1.2 on 2022-11-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_libro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
    ]
